V0.1.0 - alpha
tum-fml/vda5050_connector pull request #13
Opened 2023-06-16 07:58 UTC by jammoul271

- Removed unused msg folder

- Update configuration files. Removed unused bridge.yaml file

- Updated README

- Moved src files into new vda5050_connector

- Updated includes in header files

- Updated comments, removed usage of namespaces in header files

- Removed unused header object for Daemons.

- Created new Utils source file

- Updated state message in AGV and state mockups

- Updated tests

- Updated CMakeLists

- Removed unused launch files (Missing configuration files)

- Update knotvector type

- Removed logs and exit

- Rename the whole thing
  
- Updated the names of the nodes for more clarity. Removed the usage of the word daemon.

- Updated cmake lists

- Split configuration of nodes. And merged mqtt configuration into one file.

- Merged all nodes into one launch file. Added config file for each node.

- Updated tests

- Updated documentation

- Removed the connection publisher node and its documentation

- Updated the state aggregator to send connection state messages

- Updated documentation

- Updated launch files

- Added support for Ubuntu 16

- Updated configuration

- Updated mockups

- Added support for default ros messages for battery

- Added rate and updated subscribed channel for velocity

- Updated documentation

- Added how to run state mockup to documentation

- Updated timestamp field to timeStamp

- Added zone update connection

- Update name of instantAction topic

2023-06-16 10:49 UTC, JadKeryakos approved these changes

2023-07-01 09:30 UTC, frothm requested changes
In 4 files (see comments), the commenting of variables is not Doxygen-conform. Please change these one-line comment blocks to a format that is recognized by Doxygen. E.g. `//! ...` would work, or the commentary after the variable definition with `/*< ... */`. Reference: [Doxygen documentation](https://www.doxygen.nl/manual/docblocks.html).
Thanks a lot and best regards :)

2023-07-01 09:30 UTC, frothm commented on include/vda5050_connector/order_manager.h
Same here, not sure if Doxygen will process the `// ...` comments related to variables.

2023-07-01 09:30 UTC, frothm commented on include/vda5050_connector/vda5050node.h
Commenting of variables should be Doxygen-compatible again

2023-07-01 09:30 UTC, frothm commented on include/vda5050_connector/state_aggregator.h
Variable documentation should be Doxygen compatible.

2023-11-20 06:21 UTC, merged